### ISSUE TITLE
Exception occurs when tap <Home> button after tap license 100 times

### ISSUE THREAD

**Issue by subaru44k** [sjnyag/stamp#70]
### Procedure
![screenshot_20170804-164448](https://user-images.githubusercontent.com/10189714/28959184-4a5af5f6-7934-11e7-8ea4-ddb6a4234f3b.png)
- Tap license 100 times
- Tap `<Home>` button

### Root of cause
The system stacks fragment when License is taped.

`com.sjn.stamp.ui.activity.DrawerActivity.java`
```java
    public void navigateToBrowser(Fragment fragment, boolean addToBackStack, long selection) {
        navigateToBrowser(fragment, addToBackStack);
        mDrawer.setSelection(selection);
    }
```

So the fragment stack will be like following.
```
      #3: SettingFragment{1258d28 #47 id=0x7f1400e0 fragment_container}
        mFragmentId=#7f1400e0 mContainerId=#7f1400e0 mTag=fragment_container
        mState=1 mIndex=47 mWho=android:fragment:47 mBackStackNesting=1
        mAdded=false mRemoving=true mFromLayout=false mInLayout=false
        mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
        mRetainInstance=false mRetaining=false mUserVisibleHint=true
        mFragmentManager=FragmentManager{70e195b in HostCallbacks{57b3ad1}}
        mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
        mSavedViewState={16908292=android.view.AbsSavedState$1@9e936, 16908351=android.view.AbsSavedState$1@9e936, 2132017730=android.support.v7.widget.RecyclerView$SavedState@2ef7a41}
        Child FragmentManager{67d0be6 in SettingFragment{1258d28}}:
          FragmentManager misc state:
            mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
            mContainer=android.support.v4.app.Fragment$2@6c25527
            mParent=SettingFragment{1258d28 #47 id=0x7f1400e0 fragment_container}
            mCurState=1 mStateSaved=true mDestroyed=false
      #4: SettingFragment{9da53d4 #48 id=0x7f1400e0 fragment_container}
        mFragmentId=#7f1400e0 mContainerId=#7f1400e0 mTag=fragment_container
        mState=1 mIndex=48 mWho=android:fragment:48 mBackStackNesting=2
        mAdded=false mRemoving=true mFromLayout=false mInLayout=false
        mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
        mRetainInstance=false mRetaining=false mUserVisibleHint=true
        mFragmentManager=FragmentManager{70e195b in HostCallbacks{57b3ad1}}
        mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
        mSavedViewState={16908292=android.view.AbsSavedState$1@9e936, 16908351=android.view.AbsSavedState$1@9e936, 2132017730=android.support.v7.widget.RecyclerView$SavedState@178797d}
        Child FragmentManager{8fe0072 in SettingFragment{9da53d4}}:
          FragmentManager misc state:
            mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
            mContainer=android.support.v4.app.Fragment$2@2751cc3
            mParent=SettingFragment{9da53d4 #48 id=0x7f1400e0 fragment_container}
            mCurState=1 mStateSaved=true mDestroyed=false
            
Repeated 79 times
            
      #83: SettingFragment{eb799a6 #127 id=0x7f1400e0 fragment_container}
        mFragmentId=#7f1400e0 mContainerId=#7f1400e0 mTag=fragment_container
        mState=1 mIndex=127 mWho=android:fragment:127 mBackStackNesting=2
        mAdded=false mRemoving=true mFromLayout=false mInLayout=false
        mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
        mRetainInstance=false mRetaining=false mUserVisibleHint=true
        mFragmentManager=FragmentManager{70e195b in HostCallbacks{57b3ad1}}
        mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
        mSavedViewState={16908292=android.view.AbsSavedState$1@9e936, 16908351=android.view.AbsSavedState$1@9e936, 2132017730=android.support.v7.widget.RecyclerView$SavedState@1612fe7}
        Child FragmentManager{6a3f794 in SettingFragment{eb799a6}}:
          FragmentManager misc state:
            mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
            mContainer=android.support.v4.app.Fragment$2@9b7b23d
            mParent=SettingFragment{eb799a6 #127 id=0x7f1400e0 fragment_container}
            mCurState=1 mStateSaved=true mDestroyed=false
      #84: SettingFragment{3b3aa32 #128 id=0x7f1400e0 fragment_container}
        mFragmentId=#7f1400e0 mContainerId=#7f1400e0 mTag=fragment_container
        mState=2 mIndex=128 mWho=android:fragment:128 mBackStackNesting=1
        mAdded=true mRemoving=false mFromLayout=false mInLayout=false
        mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
        mRetainInstance=false mRetaining=false mUserVisibleHint=true
        mFragmentManager=FragmentManager{70e195b in HostCallbacks{57b3ad1}}
        mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
        mSavedViewState={16908292=android.view.AbsSavedState$1@9e936, 16908351=android.view.AbsSavedState$1@9e936, 2132017730=android.support.v7.widget.RecyclerView$SavedState@606e383}
        mContainer=android.widget.RelativeLayout{8ad5c4a V.E...... ........ 0,168-1080,1680 #7f1400e0 app:id/container}
        mView=android.widget.LinearLayout{ca4a2b9 V.E...... ........ 0,0-1080,1512}
        mInnerView=android.widget.LinearLayout{ca4a2b9 V.E...... ........ 0,0-1080,1512}
        Child FragmentManager{492f900 in SettingFragment{3b3aa32}}:
          FragmentManager misc state:
            mHost=android.support.v4.app.FragmentActivity$HostCallbacks@57b3ad1
            mContainer=android.support.v4.app.Fragment$2@723539
            mParent=SettingFragment{3b3aa32 #128 id=0x7f1400e0 fragment_container}
            mCurState=2 mStateSaved=true mDestroyed=false
```

When user tap `<Home>` button, activity will store current activity and fragment info to some place via Binder transaction to enable restore the state at next launch. However, in this defective state that information is too large to exceed the limit of binder transaction(>1Mb) caused TransactionTooLargeException.

### Log
```
08-04 16:19:07.456 23682 23682 E AndroidRuntime: FATAL EXCEPTION: main
08-04 16:19:07.456 23682 23682 E AndroidRuntime: Process: com.sjn.stamp, PID: 23682
08-04 16:19:07.456 23682 23682 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 667196 bytes
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3858)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6223)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 667196 bytes
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3630)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3850)
08-04 16:19:07.456 23682 23682 E AndroidRuntime: 	... 7 more
```

**Comment by sjnyag** [comment]
#39 ?

**Comment by sjnyag** [comment]
License dialog will be shown from Ver. 0.1.0.24.
